export const menu = {
  allCollections: [
    {
      name: "Recommended",
      subTitle: "",
      type: "recommended",
      entities: [
        {
          id: 39635441,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 39635461,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 39635453,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 76822206,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 76822202,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 39635422,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 76822275,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 76822199,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 30003172,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 30003168,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 39635401,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 39635481,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 76822282,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 76822283,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 76822260,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 76822271,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 76822272,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 76822269,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 76822233,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 76822286,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
        {
          id: 76920030,
          type: "item",
          showImg: true,
          showRibbon: false,
        },
      ],
      perRow: 1,
      collapsible: false,
      count: 21,
    },
    {
      name: "Starters",
      subTitle: "",
      type: "category",
      widgets: [
        {
          name: "Non Veg Starter",
          type: "subcategory",
          entities: [
            {
              id: 39635441,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 86144254,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 86144256,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822205,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 39635461,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 39635453,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 39635438,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822206,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822207,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822208,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
          ],
          collapsible: true,
        },
        {
          name: "Veg Starter",
          type: "subcategory",
          entities: [
            {
              id: 76822202,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 39635457,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 39635422,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822203,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822204,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
          ],
          collapsible: true,
        },
      ],
      perRow: 1,
      collapsible: false,
      count: 15,
    },
    {
      name: "Family Binge Packs",
      subTitle: "",
      type: "category",
      widgets: [
        {
          name: "Pack For 2",
          type: "subcategory",
          entities: [
            {
              id: 79526659,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 79526657,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 79526653,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 79526655,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
          ],
          collapsible: true,
        },
        {
          name: "Pack For 4",
          type: "subcategory",
          entities: [
            {
              id: 79526663,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 79526658,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 79526654,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 79526656,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
          ],
          collapsible: true,
        },
      ],
      perRow: 1,
      collapsible: false,
      count: 8,
    },
    {
      name: "Main Course",
      subTitle: "",
      type: "category",
      widgets: [
        {
          name: "Gravy- Veg",
          type: "subcategory",
          entities: [
            {
              id: 76822274,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822275,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822199,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822276,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 30003172,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822278,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822279,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822200,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822201,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 30003168,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822280,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
          ],
          collapsible: true,
        },
        {
          name: "Gravy- Non Veg",
          type: "subcategory",
          entities: [
            {
              id: 76822281,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 39635401,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 39635481,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822282,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822283,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822284,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822285,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 39635451,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
          ],
          collapsible: true,
        },
      ],
      perRow: 1,
      collapsible: false,
      count: 19,
    },
    {
      name: "Rice & Indian Breads",
      subTitle: "",
      type: "category",
      widgets: [
        {
          name: "Indian Breads",
          type: "subcategory",
          entities: [
            {
              id: 39635423,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 63076837,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822197,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822259,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822260,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822261,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822262,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822198,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
          ],
          collapsible: true,
        },
        {
          name: "Rice",
          type: "subcategory",
          entities: [
            {
              id: 76822268,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822271,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 39635409,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822272,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822269,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822273,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 39635414,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
          ],
          collapsible: true,
        },
      ],
      perRow: 1,
      collapsible: false,
      count: 15,
    },
    {
      name: "Premium Thalis",
      subTitle: "",
      type: "category",
      widgets: [
        {
          name: "Non Veg Premium Thali",
          type: "subcategory",
          entities: [
            {
              id: 76822240,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822241,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822242,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822243,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822244,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822245,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822246,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822247,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822248,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822249,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
          ],
          collapsible: true,
        },
        {
          name: "Veg Premium Thali",
          type: "subcategory",
          entities: [
            {
              id: 76822233,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 77334025,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822235,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822236,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822237,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822238,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
            {
              id: 76822239,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
          ],
          collapsible: true,
        },
      ],
      perRow: 1,
      collapsible: false,
      count: 17,
    },
    {
      name: "Desserts & Beverages",
      subTitle: "",
      type: "category",
      widgets: [
        {
          name: "Desserts",
          type: "subcategory",
          entities: [
            {
              id: 76822286,
              type: "item",
              showImg: false,
              showRibbon: false,
            },
          ],
          collapsible: true,
        },
      ],
      perRow: 1,
      collapsible: false,
      count: 1,
    },
    {
      name: "Accompaniments",
      subTitle: "",
      type: "category",
      entities: [
        {
          id: 76920030,
          type: "item",
          showImg: false,
          showRibbon: false,
        },
        {
          id: 76920031,
          type: "item",
          showImg: false,
          showRibbon: false,
        },
        {
          id: 39635400,
          type: "item",
          showImg: false,
          showRibbon: false,
        },
        {
          id: 36548561,
          type: "item",
          showImg: false,
          showRibbon: false,
        },
        {
          id: 76920032,
          type: "item",
          showImg: false,
          showRibbon: false,
        },
      ],
      perRow: 1,
      collapsible: false,
      count: 5,
    },
  ],

  items: {
    30003168: {
      id: 30003168,
      name: "Dal Makhani",
      category: "Main Course",
      description:
        "Classic creamy lentil dish made with whole black lentils, spices, butter and cream.",
      cloudinaryImageId: "rlilgps7plu0kn8xayok",
      recommended: 1,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 24900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      ribbon: {
        text: "Bestseller",
        textColor: "#ffffff",
        topBackgroundColor: "#d53d4c",
        bottomBackgroundColor: "#b02331",
      },
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: true,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    30003172: {
      id: 30003172,
      name: "Kadai Paneer",
      category: "Main Course",
      description:
        "Cottage cheese cooked with ground spices in a special indian wok called kadai.",
      cloudinaryImageId: "keyxizvmpyq9awwwdppo",
      recommended: 1,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 27500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      ribbon: {
        text: "Bestseller",
        textColor: "#ffffff",
        topBackgroundColor: "#d53d4c",
        bottomBackgroundColor: "#b02331",
      },
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: true,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    36548561: {
      id: 36548561,
      name: "Curd",
      category: "Accompaniments",
      description: " ",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 4900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "Serves 1",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    39635400: {
      id: 39635400,
      name: "Green Salad",
      category: "Accompaniments",
      description: "Healthy and nutrient loaded green salad.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 6900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "Serves 1",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    39635401: {
      id: 39635401,
      name: "Butter Chicken",
      category: "Main Course",
      description:
        "A classic chicken dish prepared in a rich sauce of tomato, butter and cream.",
      cloudinaryImageId: "foewzcgbw1wgkwo7vxlr",
      recommended: 1,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 30500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      ribbon: {
        text: "Bestseller",
        textColor: "#ffffff",
        topBackgroundColor: "#d53d4c",
        bottomBackgroundColor: "#b02331",
      },
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: true,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    39635409: {
      id: 39635409,
      name: "Jeera Rice",
      category: "Rice & Indian Breads",
      description: "Rice cooked with cumin seeds & fragrant spices.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 14800,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    39635414: {
      id: 39635414,
      name: "Ghee Rice",
      category: "Rice & Indian Breads",
      description:
        "Cooked rice with ghee being the primary ingredient to give a distinct flavour.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 15900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    39635422: {
      id: 39635422,
      name: "Paneer Malai Tikka",
      category: "Starters",
      description: "Slow-cooked paneer tikka mildly flavoured with rich cream.",
      cloudinaryImageId: "rljnlaevvajull8glpif",
      recommended: 1,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 29000,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    39635423: {
      id: 39635423,
      name: "Naan",
      category: "Rice & Indian Breads",
      description: "A leavened flatbread cooked in a tandoor (clay oven).",
      cloudinaryImageId: "a19ooacqhxpvthwhi0xz",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 4500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    39635438: {
      id: 39635438,
      name: "Chicken Irani Kebab",
      category: "Starters",
      description:
        "Chicken pieces smothered in a mildly-spiced marinade cooked in middle-eastern style.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 29900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    39635441: {
      id: 39635441,
      name: "Dhaniya Chicken Tikka",
      category: "Starters",
      description:
        "Succulent chicken marinated & flavoured with fresh coriander, grilled to perfection.",
      cloudinaryImageId: "vgkmyncx7yxcug1hvf1u",
      recommended: 1,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 29900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    39635451: {
      id: 39635451,
      name: "Mutton Rogan Josh",
      category: "Main Course",
      description:
        "Pieces of mutton braised with a gravy flavoured with garlic, ginger and aromatic spices.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 39000,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    39635453: {
      id: 39635453,
      name: "Methi Chicken Tikka Barnala",
      category: "Starters",
      description:
        "Barnala-style tender chicken tikka flavoured with aromatic methi.",
      cloudinaryImageId: "gfzzaqcde7avnhjtd2yb",
      recommended: 1,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 29900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    39635457: {
      id: 39635457,
      name: "Paneer Tikka Hariyali",
      category: "Starters",
      description: "Slow-cooked paneer tikka flavoured with coriander.",
      cloudinaryImageId: "wie9yvkxufxxqj0cec3l",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 29000,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    39635461: {
      id: 39635461,
      name: "Shahi Chicken Tikka Patiala",
      category: "Starters",
      description: "Spicy chicken tikka prepped patiala-style.",
      cloudinaryImageId: "nkmuaaqvmyxu4jwr3txi",
      recommended: 1,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 29900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    39635481: {
      id: 39635481,
      name: "Kadhai Chicken",
      category: "Main Course",
      description:
        "Flavourful chicken dish made with fresh ground kadai masala.",
      cloudinaryImageId: "w9sjhjozdckijo4bhhpd",
      recommended: 1,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 30500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    63076837: {
      id: 63076837,
      name: "Butter Naan",
      category: "Rice & Indian Breads",
      description:
        "Flatbread cooked in a tandoor & slathered with melted butter.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 5300,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      ribbon: {
        text: "Bestseller",
        textColor: "#ffffff",
        topBackgroundColor: "#d53d4c",
        bottomBackgroundColor: "#b02331",
      },
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: true,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822197: {
      id: 76822197,
      name: "Garlic Naan",
      category: "Rice & Indian Breads",
      description:
        "Fluffy flatbread cooked in a tandoor & infused with garlic flavour.",
      cloudinaryImageId: "th8qjdesm2wrk7iyheki",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 5800,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      ribbon: {
        text: "Bestseller",
        textColor: "#ffffff",
        topBackgroundColor: "#d53d4c",
        bottomBackgroundColor: "#b02331",
      },
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: true,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822198: {
      id: 76822198,
      name: "Lachha Paratha",
      category: "Rice & Indian Breads",
      description: "A layered indian flatbread made with unleavened dough",
      cloudinaryImageId: "ww9b4oucv2luck3cl4bn",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 5800,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "Serves 1",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822199: {
      id: 76822199,
      name: "Paneer Butter Masala",
      category: "Main Course",
      description:
        "Tender pieces of cottage cheese marinated and prepared in a delectable gravy.",
      cloudinaryImageId: "hu9v0vckltd8pp98dkhy",
      recommended: 1,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 29900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822200: {
      id: 76822200,
      name: "Mushroom Masala",
      category: "Main Course",
      description:
        "Delectable mushroom dish made with tomato, onions, spices and herbs.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 26900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822201: {
      id: 76822201,
      name: "Dal Tadka",
      category: "Main Course",
      description:
        "Traditional lentils finished with a tempering of spices with ghee.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 22900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822202: {
      id: 76822202,
      name: "Achari Paneer Tikka",
      category: "Starters",
      description: "Slow cooked paneer tikka in achari marination",
      cloudinaryImageId: "zcena4m8ccnauxcn8av0",
      recommended: 1,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 29000,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822203: {
      id: 76822203,
      name: "Soya Masala Malai Chaap",
      category: "Starters",
      description: "A rich dish slow-cooked in mildly-spiced flavourful cream.",
      cloudinaryImageId: "xp3mi78qeh5qlbyhyj5x",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 26500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822204: {
      id: 76822204,
      name: "Soya Tandoori Chaap",
      category: "Starters",
      description:
        "Soya chaap smeared with spiced-tangy marinade, cooked over direct flame.",
      cloudinaryImageId: "fowlftqxrobpp19rdwog",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 26500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822205: {
      id: 76822205,
      name: "Malai Chicken Tikka",
      category: "Starters",
      description:
        "Tender chicken smeared in rich cream flavoured with herbs and spices.",
      cloudinaryImageId: "gsdtt1shfzglbr1tv40x",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 29900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822206: {
      id: 76822206,
      name: "Half Tandoori Chicken - Bathinda Style",
      category: "Starters",
      description: "Bathinda-style spicy-charred tandoori chicken.",
      cloudinaryImageId: "tkdwkjjbld49v1m02lox",
      recommended: 1,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 34500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822207: {
      id: 76822207,
      name: "Tangdi Kabab - 3 Pcs",
      category: "Starters",
      description:
        "Traditional tender chicken leg pieces cooked in flavourful indian spices.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 29900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822208: {
      id: 76822208,
      name: "Chicken Kabab",
      category: "Starters",
      description:
        "Chicken pieces marinated in traditional spices and perfectly oil fried - bengaluru style.",
      cloudinaryImageId: "wwj7hrtnadfrzvk0jzvf",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 29900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822233: {
      id: 76822233,
      name: "Premium Paneer Butter Masala  Roti Thali",
      category: "Premium Thalis",
      description:
        "Paneer butter masala , 2 nos roti , 2 pcs paneer tikka  served with pickle , raita ,gulab jamun , green chutney & salad",
      cloudinaryImageId: "jclmnueykpjky5w4fgje",
      recommended: 1,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 31000,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822235: {
      id: 76822235,
      name: "Premium Matar Paneer  Roti Thali",
      category: "Premium Thalis",
      description:
        "Matar paneer , 2 nos roti served with pickle , raita ,gulab jamun, 2 pcs paneer tikka , green chutney , salad",
      cloudinaryImageId: "ya7jggbjg3bh3cxv1qmi",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 31000,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822236: {
      id: 76822236,
      name: "Premium Matar Paneer Pulao Thali",
      category: "Premium Thalis",
      description:
        "Matar paneer , pualo served with pickle , raita ,gulab jamun , 2 pcs paneer tikka , green chutney , salad",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 31000,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822237: {
      id: 76822237,
      name: "Premium Kadai Paneer Pulao Thali",
      category: "Premium Thalis",
      description:
        "Kadhai paneer , pulao served with pickle , raita ,gulab jamun, 2 pcs paneer tikka , green chutney , salad",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 31000,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822238: {
      id: 76822238,
      name: "Premium Kadai Paneer Roti Thali",
      category: "Premium Thalis",
      description:
        "Kadhai paneer , 2  nos roti served with pickle , raita ,gulab jamun,  2 pcs paneer tikka , green chutney , salad",
      cloudinaryImageId: "ya7jggbjg3bh3cxv1qmi",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 31000,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "Serves 1",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822239: {
      id: 76822239,
      name: "Premium Tadka Dal Chawal Thali",
      category: "Premium Thalis",
      description:
        "Served with pickle , raita ,gulab jamun,  2 pcs paneer tikka , green chutney , salad",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 25900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822240: {
      id: 76822240,
      name: "Premium Egg Curry Roti Thali",
      category: "Premium Thalis",
      description:
        "Egg curry , 2 nos roti served with pickle , raita ,gulab jamun , 2 pcs chicken tikka",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 25900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822241: {
      id: 76822241,
      name: "Premium Egg Curry Pulao Thali",
      category: "Premium Thalis",
      description:
        "Egg curry , pulao served with pickle , raita ,gulab jamun, 2 pcs chicken tikka",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 25900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822242: {
      id: 76822242,
      name: "Premium Butter Chicken Roti Thali",
      category: "Premium Thalis",
      description:
        "Butter chicken , 2 nos roti served with pickle , raita ,gulab jamun, 2 pcs chicken tikka",
      cloudinaryImageId: "uzyvutvipy4e3xwfseq3",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 32900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      ribbon: {
        text: "Bestseller",
        textColor: "#ffffff",
        topBackgroundColor: "#d53d4c",
        bottomBackgroundColor: "#b02331",
      },
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: true,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822243: {
      id: 76822243,
      name: "Premium Butter Chicken Pulao Thali",
      category: "Premium Thalis",
      description:
        "Butter chicken, pulao served with pickle , raita ,gulab jamun ,2 pcs chicken tikka",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 32900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822244: {
      id: 76822244,
      name: "Premium Kadhai Chicken Roti Thali",
      category: "Premium Thalis",
      description:
        "Kadhai chicken , 2 nos roti served with pickle , raita ,gulab jamun,,2 pcs chicken tikka",
      cloudinaryImageId: "dqt9mq5m1bl4fm8ghmt2",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 32900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822245: {
      id: 76822245,
      name: "Premium Kadhai Chicken Pulao Thali",
      category: "Premium Thalis",
      description:
        "Kadhai chicken , pulao served with pickle , raita ,gulab jamun ,2 pcs chicken tikka",
      cloudinaryImageId: "l6nigikde4pe60erzmle",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 32900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822246: {
      id: 76822246,
      name: "Premium Punjbai Chicken Curry Roti Thali",
      category: "Premium Thalis",
      description:
        "Punjabi chicken curry , 2 rotis served with pickle , raita ,gulab jamun,2 pcs chicken tikka",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 32900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822247: {
      id: 76822247,
      name: "Premium Punjbai Chicken Curry Pualo Thali",
      category: "Premium Thalis",
      description:
        "Punjabi chicken curry, pulao served with pickle , raita ,gulab jamun,,2 pcs chicken tikka",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 32900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822248: {
      id: 76822248,
      name: "Premium Mutton Rogan Josh Roti Thali",
      category: "Premium Thalis",
      description:
        "Mutton rogan , 2 nos roti served with pickle , raita ,gulab jamun,2 pcs chicken tikka",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 39500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822249: {
      id: 76822249,
      name: "Premium Mutton Rogan Josh Pulao Thali",
      category: "Premium Thalis",
      description:
        "Mutton rogan , pulao served with pickle , raita ,gulab jamun,,2 pcs chicken tikka",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 39500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822259: {
      id: 76822259,
      name: "Butter Garlic Naan",
      category: "Rice & Indian Breads",
      description:
        "Fluffy flatbread cooked in a tandoor, infused with garlic flavour & slathered with melted butter.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 6500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "Serves 1",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822260: {
      id: 76822260,
      name: "Chili Coiriander Naan",
      category: "Rice & Indian Breads",
      description:
        "Fluffy flatbread cooked in a tandoor & infused with flavourful chilli & coriander.",
      cloudinaryImageId: "nrjwdhgbvq4lpdhfjfrl",
      recommended: 1,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 6500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822261: {
      id: 76822261,
      name: "Tandoori Roti",
      category: "Rice & Indian Breads",
      description: "A traditional indian flatbread cooked in a clay oven.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 3500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822262: {
      id: 76822262,
      name: "Tandoori Butter Roti",
      category: "Rice & Indian Breads",
      description:
        "Classic indian tandoori flatbread slathered with melted butter.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 4300,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822268: {
      id: 76822268,
      name: "Plain Rice",
      category: "Rice & Indian Breads",
      description: "Fluffy rice cooked to perfection.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 9900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822269: {
      id: 76822269,
      name: "Pulao",
      category: "Rice & Indian Breads",
      description: "Rice flavoured with spices and cooked in rich stock.",
      cloudinaryImageId: "fedvt62s3spgcxtkvxls",
      recommended: 1,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 15900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822271: {
      id: 76822271,
      name: "Veg Tawa Biryani",
      category: "Rice & Indian Breads",
      description: "Flavourful rice with vegetables cooked.",
      cloudinaryImageId: "fspejtkjj170g8x1zqdl",
      recommended: 1,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 16900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      ribbon: {
        text: "Bestseller",
        textColor: "#ffffff",
        topBackgroundColor: "#d53d4c",
        bottomBackgroundColor: "#b02331",
      },
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: true,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822272: {
      id: 76822272,
      name: "Chicken Tawa Biryani",
      category: "Rice & Indian Breads",
      description:
        "A spicy and flavourful rice prepared by tossing cooked rice in spicy chicken mixture.",
      cloudinaryImageId: "o1wn7ovqi1nrne2q3dmc",
      recommended: 1,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 28500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      ribbon: {
        text: "Bestseller",
        textColor: "#ffffff",
        topBackgroundColor: "#d53d4c",
        bottomBackgroundColor: "#b02331",
      },
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: true,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822273: {
      id: 76822273,
      name: "Mutton Tawa Biryani",
      category: "Rice & Indian Breads",
      description:
        "A spicy and flavourful rice prepared by tossing cooked rice in spicy mutton mixture.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 34900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822274: {
      id: 76822274,
      name: "Mix Veg",
      category: "Main Course",
      description: "Mixed vegetables cooked in a curry with authentic spices.",
      cloudinaryImageId: "uu1jgl5tkue0rsoyo3kv",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 26900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822275: {
      id: 76822275,
      name: "Paneer Tikka Masala",
      category: "Main Course",
      description:
        "Tender pieces of cottage cheese marinated and prepared in a delectable gravy.",
      cloudinaryImageId: "skybaxvdpfmwmnav58fa",
      recommended: 1,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 29900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      ribbon: {
        text: "Bestseller",
        textColor: "#ffffff",
        topBackgroundColor: "#d53d4c",
        bottomBackgroundColor: "#b02331",
      },
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: true,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822276: {
      id: 76822276,
      name: "Matar Paneer",
      category: "Main Course",
      description:
        "Delicious cottage cheese cooked in a tomato based gravy with peas.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 29900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822278: {
      id: 76822278,
      name: "Palak Paneer",
      category: "Main Course",
      description:
        "A curry based cottage cheese dish made with fresh spinach and spices.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 29900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822279: {
      id: 76822279,
      name: "Kadai Mushroom",
      category: "Main Course",
      description:
        "Delicious dish made with mushrooms, onions, herbs and fresh ground kadai masala.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 26000,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822280: {
      id: 76822280,
      name: "Soya Chaap Masala",
      category: "Main Course",
      description:
        "Protein-rich indian dish made with soya chaap and a unique rich gravy.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 26000,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822281: {
      id: 76822281,
      name: "Egg Curry",
      category: "Main Course",
      description:
        "Eggs cooked in a rich and delectable tomato-based curry with spices.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 24900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822282: {
      id: 76822282,
      name: "Punjbai Chicken Curry",
      category: "Main Course",
      description:
        "Delectable chicken dish prepared in a thick and rich flavourful gravy.",
      cloudinaryImageId: "ucqbzvsv9xa0y77n5xwx",
      recommended: 1,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 30500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822283: {
      id: 76822283,
      name: "Chiken Tikka Masala",
      category: "Main Course",
      description: "Roasted and marinated chicken cooked in a spicy gravy.",
      cloudinaryImageId: "hzsvtnwzmyzrw8t2lmo6",
      recommended: 1,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 30500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      ribbon: {
        text: "Bestseller",
        textColor: "#ffffff",
        topBackgroundColor: "#d53d4c",
        bottomBackgroundColor: "#b02331",
      },
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: true,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822284: {
      id: 76822284,
      name: "Chicken Kolhapuri",
      category: "Main Course",
      description:
        "A chicken curry that is full of the rich, varied, spicy kolhapuri flavors.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 30500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822285: {
      id: 76822285,
      name: "Chicken Lababdar",
      category: "Main Course",
      description:
        "A delectable blend of aromatic spices and tender chicken pieces.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 30500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76822286: {
      id: 76822286,
      name: "Gulab Jamun",
      category: "Desserts & Beverages",
      description:
        "Sweet and sumptuous dough balls soaked in cinnamon flavoured sugar syrup",
      cloudinaryImageId: "odr9lgc0xtuxhejrknok",
      recommended: 1,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 9900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76920030: {
      id: 76920030,
      name: "Raita",
      category: "Accompaniments",
      description: "A delish side dish made with fresh curd and vegetables.",
      cloudinaryImageId: "vo4btqa8dzjkemkizpcp",
      recommended: 1,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 6900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "Serves 1",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76920031: {
      id: 76920031,
      name: "Green Chutney",
      category: "Accompaniments",
      description:
        "A flavourful condiment made with mint and corriander leaves.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 4900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "Serves 1",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    76920032: {
      id: 76920032,
      name: "Roasted Papad (2 Nos)",
      category: "Accompaniments",
      description: "Crispy and delish appetizer.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 6900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "Serves 1",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    77334025: {
      id: 77334025,
      name: "Premium Paneer Butter Masala Pulao Thali",
      category: "Premium Thalis",
      description:
        "Paneer butter masala ,pualo rice  served with pickle , raita ,gulab jamun , 2 pcs paneer tikka , green chutney , salad",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 31000,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    79526653: {
      id: 79526653,
      name: "Butter Chicken Binge Pack For 2",
      category: "Family Binge Packs",
      description:
        "A binge pack of tender butter chicken, naan (2pcs) & gulab jamun (2 pcs) that serves 2.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 63900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    79526654: {
      id: 79526654,
      name: "Butter Chicken Binge Pack For 4",
      category: "Family Binge Packs",
      description:
        "A wholesome binge pack of butter chicken, naan (4pcs) & gulab jamun (4 pcs) that serves 4.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 124900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    79526655: {
      id: 79526655,
      name: "Kadai Chicken Binge Pack For 2",
      category: "Family Binge Packs",
      description:
        "A binge pack of melt-in-mouth kadai chicken, naan (2pcs) & gulab jamun (2 pcs) that serves 2.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 63900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    79526656: {
      id: 79526656,
      name: "Kadai Chicken Binge Pack For 4",
      category: "Family Binge Packs",
      description:
        "A wholesome binge pack of kadai chicken, naan (4pcs) & gulab jamun (4 pcs) that serves 4.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 124900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    79526657: {
      id: 79526657,
      name: "Kadai Paneer Binge Pack For 2",
      category: "Family Binge Packs",
      description:
        "A pack of tempting binge pack of kadai paneer, naan (2pcs) & gulab jamun (2 pcs) that serves 2.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 57500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    79526658: {
      id: 79526658,
      name: "Kadai Paneer Binge Pack For 4",
      category: "Family Binge Packs",
      description:
        "A surprising binge pack of kadai paneer, naan (4pcs) & gulab jamun (4 pcs) that serves 4.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 114900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    79526659: {
      id: 79526659,
      name: "Paneer Butter Masala Binge Pack For 2",
      category: "Family Binge Packs",
      description:
        "A delectable binge pack of paneer butter masala, naan (2pcs) & gulab jamun (2 pcs) that serves 2.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 57500,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    79526663: {
      id: 79526663,
      name: "Paneer Butter Masala Binge Pack For 4",
      category: "Family Binge Packs",
      description:
        "A wholesome binge pack of paneer butter masala, naan (4pcs) & gulab jamun (4 pcs) that serves 4.",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 1,
      enabled: 1,
      displayOrder: 0,
      price: 114900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "VEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    86144254: {
      id: 86144254,
      name: "Achari Chicken Tikka",
      category: "Starters",
      description: " ",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 29900,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
    86144256: {
      id: 86144256,
      name: "Ajwaini Fish Tikka",
      category: "Starters",
      description: "Ajwaini fish tikka",
      cloudinaryImageId: "",
      recommended: 0,
      inStock: 1,
      isVeg: 0,
      enabled: 1,
      displayOrder: 0,
      price: 42000,
      variants_new: { exclude_list: [], variant_groups: [] },
      cropChoices: 2,
      itemScore: 0,
      itemDiscount: 0,
      isPopular: 0,
      restId: "108899",
      showMC: 0,
      attributes: {
        portionSize: "",
        vegClassifier: "NONVEG",
        accompaniments: "",
      },
      isHealthy: false,
      isBestSeller: false,
      itemNudgeType: "",
      isGuiltFree: false,
    },
  },
};

